# Generated by Django 4.2.6 on 2023-11-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_categories_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='approval',
            field=models.CharField(default='false', max_length=255),
        ),
    ]
