# Generated by Django 4.2.6 on 2023-11-26 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0009_alter_salescount_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salescount',
            name='donor',
        ),
        migrations.AddField(
            model_name='salescount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salescount',
            name='sales',
            field=models.IntegerField(),
        ),
    ]
