# Generated by Django 4.2.6 on 2023-11-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_salescount_donor_salescount_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescount',
            name='oldsales',
            field=models.IntegerField(default=0),
        ),
    ]
