# Generated by Django 4.2.6 on 2023-11-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_salescount_oldsales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescount',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
