# Generated by Django 4.2.6 on 2023-11-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_salescount_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='user',
        ),
    ]
