# Generated by Django 4.2.6 on 2023-11-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_categories_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_pet_name', models.CharField(max_length=255)),
                ('home_price', models.IntegerField()),
                ('home_pet_image', models.ImageField(blank=True, null=True, upload_to='homepets/')),
            ],
        ),
    ]
