# Generated by Django 4.2.6 on 2023-11-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_homepets'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepets',
            name='offer_percent',
            field=models.IntegerField(default=0),
        ),
    ]
