# Generated by Django 4.2.6 on 2023-11-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_homepets_offer_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='captcha',
            field=models.IntegerField(default=0),
        ),
    ]
