# Generated by Django 4.2.6 on 2023-11-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_pet_captcha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pets_view',
            field=models.CharField(default='false', max_length=255),
        ),
    ]
