# Generated by Django 4.2.6 on 2023-11-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_pet_pets_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescount',
            name='newdisapprove',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salescount',
            name='olddisapprove',
            field=models.IntegerField(default=0),
        ),
    ]
